@be_dunnit_HostAddress = http://localhost:5235

GET {{be_dunnit_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{be_dunnit_HostAddress}}/config/
Accept: application/json

###